In [ ]:
print("Hello")


Hello


# New Section

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
a=2
a


2

In [ ]:
a

2

In [ ]:
a=2
b=3
a
b


3

In [ ]:
print(str(a)
)

2


In [ ]:
type(a)


int

In [ ]:
s="RJ College"

In [ ]:
type(s)

str


**nump li**



nump library

In [ ]:
ls


sample_data/


In [ ]:
!ls sample_data

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


$y=x^2$
y

In [ ]:
a=10


In [ ]:
a

10

In [ ]:
print("hello")

hello


$y=x$2
y

$y=x^2$


https://numpy.org/doc/stable/user/whatisnumpy.html


In [ ]:
a=[1,2,3]
type(a)

list

In [ ]:
b=[4,5,6]
type(b)

list

In [ ]:
c=[]
for i in range(len(a)):
    c.append(a[i]+b[i])
c


[5, 7, 9]

In [ ]:
import time
print("sleeping")
time.sleep(30)
print("done sleeping")


sleeping
done sleeping


In [ ]:
!ls /bin

bash	       hostname       su
bunzip2        journalctl     sync
bzcat	       kill	      systemctl
bzcmp	       kmod	      systemd
bzdiff	       less	      systemd-ask-password
bzegrep        lessecho       systemd-escape
bzexe	       lessfile       systemd-hwdb
bzfgrep        lesskey	      systemd-inhibit
bzgrep	       lesspipe       systemd-machine-id-setup
bzip2	       ln	      systemd-notify
bzip2recover   login	      systemd-sysusers
bzless	       loginctl       systemd-tmpfiles
bzmore	       ls	      systemd-tty-ask-password-agent
cat	       lsblk	      tar
chgrp	       lsmod	      tempfile
chmod	       mkdir	      touch
chown	       mknod	      true
cp	       mktemp	      udevadm
dash	       more	      ulockmgr_server
date	       mount	      umount
dd	       mountpoint     uname
df	       mv	      uncompress
dir	       networkctl     vdir
dmesg	       nisdomainname  wdctl
dnsdomainname  pidof	      which
domainname     ps	      ypdomainname
echo	       pwd	      zcat
egrep	     

In [ ]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.ndim

2

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.dtype.name

'int64'

In [ ]:
a.itemsize

8

In [ ]:
a.size

15

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b=np.array([12,13,15])
b.dtype

dtype('int64')

In [ ]:
b=np.array([[12,13,15],[10,20,30]])
b


array([[12, 13, 15],
       [10, 20, 30]])

In [ ]:
c=b.reshape(3,2)
c

array([[12, 13],
       [15, 10],
       [20, 30]])

In [ ]:
a=np.array([['a','b','c','d','e'],['f','g','h','i','j']])
a


array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U1')

In [ ]:
a.dtype

dtype('<U1')

In [ ]:
a.itemsize

4

In [ ]:
a.size


10

In [ ]:
a.ndim


2

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

1

In [ ]:
a.itemsize

8

In [ ]:
a.size

3

In [ ]:
import numpy as np
np.__version__


'1.19.5'

In [ ]:
list1=[]
list1

[]

In [ ]:
type(list1)

list

In [ ]:
list2=list(range(10))
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
print("list in the form of string")
list3=[str(c)  for c in list2]
list3

list in the form of string


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [ ]:
print("***************************List of Different Data Types******************************")
list4=[1,1.2,'abc',True]
list4

***************************List of Different Data Types******************************


[1, 1.2, 'abc', True]

In [ ]:
#display datatype of each element
[type(item) for item in list4]

[int, float, str, bool]

In [ ]:
[str(c)  for c in list2]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [ ]:
#Array in Python Vs List in Numpy
#Python Array
import array as ar
L=list(range(10))
A=ar.array('i',L)     # i indicates Integer
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as  np     #numpy array
b=np.array([10,20,30])
b


array([10, 20, 30])

In [ ]:
b.dtype

dtype('int64')

In [ ]:
b.ndim

1

In [ ]:
b.itemsize

8

In [ ]:
b.size

3

In [ ]:
import numpy as  np     #automatic (Implicit)conversion
c=np.array([10.2,20,30])
c
#Explicit Conversion
d=np.array([1,2,3,4],dtype='float32')
d




array([10.2, 20. , 30. ])

In [ ]:
#Nested List result in multidimensional arrray
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
#For matrix conversion you need all element zero
#create 10 length array filled with zero
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#2 dimensional array of zero
np.zeros((2,5),dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#2 dimensional array of Ones
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#Createa 3x5 array filled with 3.0
np.full((3,5),3.0)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [ ]:
#filled a array with linear sequence with difference of 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#with difference of 3
np.arange(0,32,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
#creation of array of evenly spaced values for the given range
#create 4 values in the ranges of 0 to 2  , values  2/4= 0.5   ,so  values will be 0.0,0.5,1.0,1.5
np.linspace(0,2,4)

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [ ]:
#Create array of random values between 0 and 1
np.random.random((3,4))

array([[0.21052345, 0.91982642, 0.84279565, 0.31560533],
       [0.94203681, 0.01863101, 0.16763466, 0.97166606],
       [0.92269178, 0.07565191, 0.51392389, 0.99954677]])

In [ ]:
#Create a 3x3 array of normally distributed random values
#with mean=0 and SD=1  and (3,3) is dimension
np.random.normal(0,1,(3,3))

array([[-1.49594416, -0.32805112, -1.29339201],
       [ 2.41509197,  0.68269266, -0.87076041],
       [ 0.11520028,  0.14670773,  0.70436471]])

In [ ]:

#Create a 3x3 array of random integers in the interval [0,10]
np.random.randint(0,10,(3,3)) 
#starting range,last range,dimension

array([[2, 0, 6],
       [8, 9, 7],
       [8, 7, 0]])

In [ ]:
#Create 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Create empty array
np.empty(3)

array([1., 1., 1.])

In [ ]:
import numpy as np   #when we dont have data sets and it is used for probability distribution
np.random.seed(30)
x1=np.random.randint(50,size=6)
x1


array([ 0, 17,  4, 27, 48,  0])

In [ ]:
#create 3 dimensional array seed=100 values can go to 300
#whenever u have to create multidimensional array
np.random.seed(100)
x2=np.random.randint(200,size=(2,2))  #2  dimensional 2 rows 2 columns
x2

array([[  8,  24],
       [ 67, 103]])

In [ ]:
#create 3 dimensional array seed=100 values can go to 300
#whenever u have to create multidimensional array
np.random.seed(100)
x2=np.random.randint(200,size=(3,2,1))  #2  dimensional 2 rows 1 columns 3 sets we get
x2

array([[[  8],
        [ 24]],

       [[ 67],
        [103]],

       [[ 87],
        [ 79]],

       [[176],
        [138]],

       [[ 94],
        [180]]])

In [ ]:
#create 3 dimensional array seed=100 values can go to 300
#whenever u have to create multidimensional array
np.random.seed(100)
x2=np.random.randint(200,size=(4,3,2,1))  #2  dimensional 2 rows 1 columns  3 sets 4 times
x2

array([[[[  8],
         [ 24]],

        [[ 67],
         [103]],

        [[ 87],
         [ 79]]],


       [[[176],
         [138]],

        [[ 94],
         [180]],

        [[ 98],
         [ 53]]],


       [[[ 66],
         [ 14]],

        [[ 34],
         [ 24]],

        [[143],
         [107]]],


       [[[ 60],
         [ 58]],

        [[144],
         [137]],

        [[ 93],
         [ 86]]]])

In [ ]:
#create 3 dimensional array seed=100 values can go to 300
#whenever u have to create multidimensional array
np.random.seed(100)
x2=np.random.randint(200,size=(5,4,3,2,1))  #2  dimensional 2 rows 1 columns  3 sets 4 times  5 sets
x2

array([[[[[  8],
          [ 24]],

         [[ 67],
          [103]],

         [[ 87],
          [ 79]]],


        [[[176],
          [138]],

         [[ 94],
          [180]],

         [[ 98],
          [ 53]]],


        [[[ 66],
          [ 14]],

         [[ 34],
          [ 24]],

         [[143],
          [107]]],


        [[[ 60],
          [ 58]],

         [[144],
          [137]],

         [[ 93],
          [ 86]]]],



       [[[[130],
          [155]],

         [[108],
          [132]],

         [[159],
          [129]]],


        [[[141],
          [100]],

         [[  4],
          [ 91]],

         [[187],
          [ 67]]],


        [[[135],
          [ 49]],

         [[175],
          [193]],

         [[ 61],
          [ 14]]],


        [[[183],
          [199]],

         [[ 80],
          [  2]],

         [[121],
          [105]]]],



       [[[[147],
          [ 63]],

         [[181],
          [ 27]],

         [[ 56],
          [113]]],


      

In [ ]:
x2.shape   #dimesion=5x4x3x2x1

(5, 4, 3, 2, 1)

In [ ]:

x2.ndim    #total=5 axis

5

In [ ]:
x2.size

120

In [ ]:
#how many bytes used for storing 120
x2.nbytes

960

In [ ]:
#how much memory required for storing single element of array
x2.itemsize

8

# New Section